name: Prerelease Linux pipeline

on:
  push:
    branches:
      - '*'
env:
  TAG: 1.7.4
  GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
  AWS_S3_BUCKET_NAME: "nr-downloads-logging-testing"
  AWS_S3_LOCK_BUCKET_NAME: "logging-ci-lock-testing"
  AWS_REGION: "us-east-1"
  DOCKER_PUBLISH: false

jobs:
  publishing-to-s3:
    name: Publish linux artifacts into s3 test bucket
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 1
      matrix:
        assetsType:
          - "deb"
          - "rpm"

    steps:
      - name: Publish ${{ matrix.assetsType }} to S3 action
        uses: newrelic/infrastructure-publish-action@v1.0.4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LOGGING_AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LOGGING_AWS_SECRET_ACCESS_KEY_STAGING }}
          AWS_ROLE_ARN: ${{ secrets.LOGGING_AWS_ROLE_ARN_STAGING }}
          AWS_ROLE_SESSION_NAME: ${{ secrets.LOGGING_AWS_SECRET_ACCESS_KEY_STAGING }}
        with:
          tag: ${{env.TAG}}
          app_name: "td-agent-bit"
          repo_name: "newrelic/fluent-bit-package"
          schema: "custom"
          schema_url: "https://raw.githubusercontent.com/newrelic/fluent-bit-package/main/schemas/fb-linux.yml"
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket_name: ${{ env.AWS_S3_BUCKET_NAME }}
          aws_s3_lock_bucket_name: ${{ env.AWS_S3_LOCK_BUCKET_NAME }}
          run_id: ${{ github.run_id }}
          aws_region: ${{ env.AWS_REGION }}
          aws_role_session_name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          # used for signing package stuff
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          gpg_private_key_base64: ${{ env.GPG_PRIVATE_KEY_BASE64 }}
